#region --- Copyright Information --- 
/*
 *******************************************************************
|                                                                   |
|           OpenNETCF Smart Device Framework 2.2                    |
|                                                                   |
|                                                                   |
|       Copyright (c) 2000-2008 OpenNETCF Consulting LLC            |
|       ALL RIGHTS RESERVED                                         |
|                                                                   |
|   The entire contents of this file is protected by U.S. and       |
|   International Copyright Laws. Unauthorized reproduction,        |
|   reverse-engineering, and distribution of all or any portion of  |
|   the code contained in this file is strictly prohibited and may  |
|   result in severe civil and criminal penalties and will be       |
|   prosecuted to the maximum extent possible under the law.        |
|                                                                   |
|   RESTRICTIONS                                                    |
|                                                                   |
|   THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES           |
|   ARE CONFIDENTIAL AND PROPRIETARY TRADE                          |
|   SECRETS OF OPENNETCF CONSULTING LLC THE REGISTERED DEVELOPER IS |
|   LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET    |
|   CONTROLS AS PART OF A COMPILED EXECUTABLE PROGRAM ONLY.         |
|                                                                   |
|   THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED      |
|   FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE        |
|   COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE       |
|   AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT  |
|   AND PERMISSION FROM OPENNETCF CONSULTING LLC                    |
|                                                                   |
|   CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON       |
|   ADDITIONAL RESTRICTIONS.                                        |
|                                                                   |
 ******************************************************************* 
*/
#endregion



//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNETCF.Net.Mail {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenNETCF.Net.Mail.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Async operation cancelled..
        /// </summary>
        internal static string Async_OperationCancelled {
            get {
                return ResourceManager.GetString("Async_OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message must contain a From sender address..
        /// </summary>
        internal static string SmtpClientFromNotValid {
            get {
                return ResourceManager.GetString("SmtpClientFromNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to host {0}..
        /// </summary>
        internal static string SmtpClientHostConnectionTimeout {
            get {
                return ResourceManager.GetString("SmtpClientHostConnectionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting response from host {0}. Error: {1}.
        /// </summary>
        internal static string SmtpClientHostErrorGetResponse {
            get {
                return ResourceManager.GetString("SmtpClientHostErrorGetResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error receiving data from host {0}. 	SmtpClientHostErrorTxing	Error sending data to host {0}. Error: {1}.
        /// </summary>
        internal static string SmtpClientHostErrorRxing {
            get {
                return ResourceManager.GetString("SmtpClientHostErrorRxing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending data to host {0}. Error: {1}.
        /// </summary>
        internal static string SmtpClientHostErrorTxing {
            get {
                return ResourceManager.GetString("SmtpClientHostErrorTxing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host value cannot be empty string..
        /// </summary>
        internal static string SmtpClientHostValueEmpty {
            get {
                return ResourceManager.GetString("SmtpClientHostValueEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid host specified..
        /// </summary>
        internal static string SmtpClientHostValueInvalid {
            get {
                return ResourceManager.GetString("SmtpClientHostValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host value cannot be null..
        /// </summary>
        internal static string SmtpClientHostValueNull {
            get {
                return ResourceManager.GetString("SmtpClientHostValueNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An asynchronous call is already in progress. It must be completed before you can call this method..
        /// </summary>
        internal static string SmtpClientInAsyncCall {
            get {
                return ResourceManager.GetString("SmtpClientInAsyncCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation cannot be performed while a message is being sent..
        /// </summary>
        internal static string SmtpClientInvalidOperationDuringSend {
            get {
                return ResourceManager.GetString("SmtpClientInvalidOperationDuringSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port cannot be less than zero..
        /// </summary>
        internal static string SmtpClientInvalidPortNumber {
            get {
                return ResourceManager.GetString("SmtpClientInvalidPortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message cannot be null..
        /// </summary>
        internal static string SmtpClientMessageNull {
            get {
                return ResourceManager.GetString("SmtpClientMessageNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain {0} supplied for SmtpCredentials is not valid..
        /// </summary>
        internal static string SmtpClientNetCredsDomainInvalid {
            get {
                return ResourceManager.GetString("SmtpClientNetCredsDomainInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message must contain a valid to address..
        /// </summary>
        internal static string SmtpClientToNotValid {
            get {
                return ResourceManager.GetString("SmtpClientToNotValid", resourceCulture);
            }
        }
    }
}
